apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  labels:
    app: learnup-chat-service
data:
  PORT: "3006"
  SERVICE: "chat Service"
  MONGO_URI: "mongodb+srv://thakeyudheen525:m6HkTA2eX8AstxcH@cluster0.bscnpma.mongodb.net/"
  FRONTEND_URL: "http://localhost:5173"
  ACCESS_TOKEN_SECRET: "password"
  REFRESH_TOKEN_SECRET: "thisispassword"
